### ISSUE TITLE
fix:OO) Choose instructor for a certain selected course.

### ISSUE THREAD

**Issue by Ahmed-cmd-web** [Ahmed-cmd-web/DATABASED#135]
According to the milestone questions:
  _2.3.I, you should insert a new record. On the other hand, in 2.3.OO, you should
  update an existing record on the table with the chosen instructor._

#121 (This was the pr merged)

**Comment by MostafaVT** [comment]
### _According to the **UPDATED** milestone questions:_
- This atrrbuite should be **added as input** `@current_semester_code VARCHAR40) `
