### ISSUE TITLE
I) Link student to course with Specific instructor

### ISSUE THREAD

**Issue by MostafaVT** [Ahmed-cmd-web/DATABASED#73]
i. Type: Stored Procedure
ii. Name: Procedures_AdminLinkStudent
iii. Input: Instructor Id int, student ID int, course ID, and semester code varchar (40)
iv. Output: Nothing

**Comment by Ahmed-cmd-web** [comment]
In 2.3.I, you have to assume that the slotID given is for a slot that already exists in
the slot table
